"""Add company field to questions

Revision ID: 16cf1cf3b598
Revises: cb05b27c0737
Create Date: 2025-11-19 07:55:12.235690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16cf1cf3b598'
down_revision = 'cb05b27c0737'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('company', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'company')
    # ### end Alembic commands ###

