"""Add feedback column to interview_sessions

Revision ID: 376dcf98d32c
Revises: 8570af889e50
Create Date: 2025-11-18 23:43:56.240331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '376dcf98d32c'
down_revision = '8570af889e50'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_sessions', sa.Column('feedback', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'feedback')
    # ### end Alembic commands ###

