"""Add stage_statistics to interview_sessions

Revision ID: 8570af889e50
Revises: 6f4dc1c3a6c2
Create Date: 2025-11-18 22:20:06.599749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8570af889e50'
down_revision = '6f4dc1c3a6c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_sessions', sa.Column('stage_statistics', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'stage_statistics')
    # ### end Alembic commands ###

