"""remove_screen_recording_column

Revision ID: cfcfc919050b
Revises: 16cf1cf3b598
Create Date: 2025-11-19 08:28:22.702832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfcfc919050b'
down_revision = '16cf1cf3b598'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the screen_recording column from interview_sessions table
    op.drop_column('interview_sessions', 'screen_recording')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Re-add the screen_recording column if we need to rollback
    op.add_column('interview_sessions', sa.Column('screen_recording', sa.Text(), nullable=True))
    # ### end Alembic commands ###

